name: Deploy Laravel to Namecheap

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Test SSH connection
        run: |
          ssh -vvv -p 21098 sunnenlp@199.188.201.252 "echo SSH OK"